config/routes.rb
Rails.application.routes.draw do

  resources :companies do
      resources :notes
        resources :tasks do
          member do
            put :complete
            delete :feed_destroy
          end
      end
   end

   resources :organizations do
     get 'search'
   end

   root to: "staticpages#index"

   resources :feeds, only: :index
   get 'staticpages/index'
   get 'staticpages/show'



   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        invitations: 'users/invitations'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description,presence: true
  belongs_to :organization
  belongs_to :company
  belongs_to :user
  belongs_to :assigned, class_name: "User", foreign_key: "assign_to"
  has_one :feed, as: :feedable, dependent:  :destroy


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @organization = current_user.organization
    @users = @organization.users
    @company = Company.find(params[:company_id])
    @tasks = @company.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @organization = current_user.organization
    @users = @organization.users
    @company = Company.find(params[:company_id])
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
   @organization = current_user.organization
   @users = @organization.users
   @user = current_user
   @company = Company.find(params[:company_id])
   @task = @company.tasks.new

   respond_to do |format|
        format.html
        format.js
      end
  end

  # GET /tasks/1/edit
  def edit
    @organization = current_user.organization
    @users = @organization.users
    @user = current_user
    @company = Company.find(params[:company_id])
    @task = Task.find(params[:id])

    respond_to do |format|
        format.html
        format.js
      end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @organization = current_user.organization
    @users = @organization.users
    @user = current_user
    @company = Company.find(params[:company_id])
    @task = Task.new(task_params)
    # @task.assign_to = User.find(params[:task][:assign_to])

    respond_to do |format|
      if @task.save
        format.html { redirect_to company_task_path(@company, @task), notice: 'Task was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update

    @organization = current_user.organization
    @users = @organization.users
    @user = current_user
    @company = Company.find(params[:company_id])
    @task = Task.find(params[:id])
    @feed = @task.feed


      respond_to do |format|
          if @task.update_attributes(task_params)

            if @feed
                  @feed.update_attributes(content: @task.description)
                else
            end
                  format.html { redirect_to company_task_path(@company, @task), notice: 'Task was successfully updated.' }
                  format.js
                  format.json { render :show, status: :ok, location: @task }
            else

                  format.html { render :edit }
                  format.js
                  format.json { render json: @task.errors, status: :unprocessable_entity }

            end
         end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @organization = current_user.organization
    @users = @organization.users
    @user = current_user
    @company = Company.find(params[:company_id])
    @task = Task.find(params[:id])
    @feed = @task.feed

    @task.destroy
    respond_to do |format|
      format.html { redirect_to company_tasks_path(@company), notice: 'Task was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  def complete
    @organization = current_user.organization
    @user = current_user
    @company = Company.find(params[:company_id])
    @task = @company.tasks.find(params[:id])

    if @task.update_attributes(completed_at: Date.today, completed_by: current_user.id, is_completed: true)
      @feed = @task.build_feed(organization_id: @organization.id, company_id: @company.id, content: @task.description)
      @feed.save
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :company_id, :completed_on, :user_id, :organization_id, :assign_to, :is_completed)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_for [@company, @task],html: { id: 'new_task'},remote: true do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
          <h4 class="modal-title" id="myModalLabel">Task</h4>
      </div>

  <div class="modal-body">

    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control"%>
    </div>


    <div class="form-group">
      <%= f.label :completed_on %><br/>
      <div class="form-group">
            <div class='input-group date datetimepicker' id='datetimepicker2'>
                <%= f.text_field :completed_on, class: "form-control", data: { behavior: "datetimepicker" }%>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>

      <%= f.hidden_field :company_id, value: @company.id %>
      <%= f.hidden_field :user_id, value: @user.id %>
      <%= f.hidden_field :organization_id, value: current_user.organization.id %>

    <div class="form-group">
      <%= f.label :Assign_to %><br/>
      <%= f.select :assign_to, options_from_collection_for_select(@users, "id", "email"),class: "form-control" %><br />
    </div>

  </div>

  <div class="modal-footer">
    <div class="actions form-group">
      <%= f.submit class: "btn btn-default btn-success form-control" %>
    </div>
  </div>

    <% end %>
  </div>
</div>

app/views/tasks/_form1.html.erb
    <%= form_for [@company, @task],html: { id: 'new_task'},remote: true do |f| %>
          <% if @task.errors.any? %>

              <div id="error_explanation">
                <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

                <ul>
                    <% @task.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                </ul>
              </div>

         <% end %>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control" %>
        </div>


        <div class="form-group">
          <%= f.label :completed_on %><br/>
          <div class="form-group">
                <div class='input-group date datetimepicker' id='datetimepicker1'>
                    <%= f.text_field :completed_on, class: "form-control" %>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>

        </div>

        <%= f.hidden_field :company_id, value: @company.id %>
        <%= f.hidden_field :user_id, value: @user.id %>
        <%= f.hidden_field :organization_id, value: current_user.organization.id %>

       <div class="form-group">
            <%= f.label :Assign_to %><br/>
            <%= f.select :assign_to, options_from_collection_for_select(@users, "id", "email"),class: "form-control" %><br />
        </div>


        <div class="form-group actions">
          <%= f.submit class: "btn btn-default btn-success" %>
        </div>
  <% end %>

app/views/tasks/_task.html.erb
<tr data-task-id='<%= task.id%>'>
  <td>
      <div class="media">
              <div class="media-left">

              </div>
              <div class="media-body">
                <div class="media-heading">
                    <%= link_to complete_company_task_path(@company, task), method: :put,remote: true,
                     style: 'margin-right:10px;' do %>
                     <%= icon 'square-o '%>
                     <%end%>
                     <%=  task.completed_on.nil? ? '-' :  task.completed_on.to_date %>
                     <%= task.description %>
                </div>
                <%= task.assigned.nil? ? '-' : task.assigned.username %>
                &nbsp;&nbsp;

                <%= link_to edit_company_task_path(@company,task),remote: true,
                'data-toggle': "modal",'data-target': "#myModal", style: 'margin-right:10px;' do %>
                <%= icon 'pencil'%>
                Edit
                <%end%>


                <%= link_to company_task_path(@company,task), remote: true,
                method: :delete, data: { confirm: 'Are you sure?' },
                style: 'margin-right:10px;' do %>
                <%= icon 'trash'%>
                Delete
                <%end%>
              </div>
        </div>
    </td>

</tr>

app/views/tasks/complete.js.erb
<% if @task.errors.any? %>

<% else %>
$("table#company_feed tbody").prepend('<%= j render partial:'companies/feed', :locals => {:feed => @feed } %>');
$("table#feed tbody").prepend('<%= j render partial:'feeds/feed', :locals => {:feed => @feed } %>');
$("#company_task tr[data-task-id='<%= @task.id %>']").remove();
<% end %>

app/views/tasks/create.js.erb
<% if @task.errors.any? %>


<% else %>
  $('#myModal').modal("hide");
  $("table#task tbody").prepend('<%= j render partial:'task', :locals => {:task => @task } %>');
  $("table#company_task tbody").prepend("<%= j render partial: 'task', :locals => {:task => @task } %>");
  $("#task_description").val("");
  $("#task_completed_on").val("");

  // $('#new_task').remove()
  // $('#new_link').show()
<% end %>

app/views/tasks/destroy.js.erb
$("#company_task tr[data-task-id='<%= @task.id %>']").remove();
<% if @feed %>
$("tr[data-company-feed-id='<%=@feed.id%>']").remove()
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', company_task_path(@company,@task) %> |
<%= link_to 'Back',  company_tasks_path(@company) %>

app/views/tasks/edit.js.erb
$('#myModal').html('<%= j render partial:'form' %>');
CRM.init();

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table class="table table-striped table-bordered table-hover" id="task">
  <thead>
    <tr>
      <th>Description</th>
      <th>Company</th>
      <th>Completed on</th>
      <th>Created by</th>
      <th>Assign_to</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @tasks %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_company_task_path(@company), id: 'new_link', remote: true,'data-toggle': "modal",'data-target': "#myModal" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>


<%= link_to 'Back', company_tasks_path(@company) %>

app/views/tasks/new.js.erb
// $('#new_link').hide().after('<%= j render partial:'form' %>')
$('#myModal').html('<%= j render partial:'form' %>')

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @task.company.name %>
</p>

<p>
  <strong>Completed on:</strong>
  <%= @task.completed_on %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @task.user.email %>
</p>

<p>
  <strong>Assign to:</strong>
  <%= @task.assigned.email %>
</p>

<p>
 <strong>Status</strong>
 <%= @task.is_completed %>
</p>

  <% if @task.is_completed == false %>
  
        <%= form_for [@company, @task] do |f| %>
         
         <div>
          <%= f.label :Status %>
          <%= f.check_box :is_completed %> Completed</br></br>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>

        <% end %>
<% end %>      



<%= link_to 'Edit', edit_company_task_path(@company,@task) %> |
<%= link_to 'Back', company_tasks_path(@company) %>

app/views/tasks/update.js.erb
$('#myModal').modal("hide");
$("tr[data-task-id='<%= @task.id %>']").replaceWith('<%= j render partial: 'task', :locals => {:task => @task } %>');

<% if @feed %>
$("tr[data-feed-id='<%= @feed.id%>']").replaceWith('<%= j render partial: 'feeds/feed', :locals => {:feed => @feed } %>');
$("tr[data-company-feed-id='<%= @feed.id%>']").replaceWith('<%= j render partial: 'companies/feed', :locals => {:feed => @feed } %>');
<% end %>