config/routes.rb
Rails.application.routes.draw do

  resources :companies do
      resources :notes
        resources :tasks do
          member do
            put :complete
            delete :feed_destroy
          end
      end
   end

   resources :organizations do
     get 'search'
   end

   root to: "staticpages#index"

   resources :feeds, only: :index
   get 'staticpages/index'
   get 'staticpages/show'



   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        invitations: 'users/invitations'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  require 'slack-notifier'
  validates :name, :presence => {message: "name must be present"}
  validates :email, :presence =>{message: "email must be present"}
  validates :contact, presence:true,length: { in: 6..10 },numericality: { only_integer: true }

  belongs_to :organization, optional: :true
  has_many :notes, dependent:  :destroy
  has_many :tasks, dependent:  :destroy
  has_many :feeds, dependent:  :destroy
  has_many :mobile_numbers, dependent: :destroy
  accepts_nested_attributes_for :mobile_numbers, reject_if: :all_blank, allow_destroy: true

  after_create :notification_send

  private

  def notification_send

    notifier = Slack::Notifier.new "https://hooks.slack.com/services/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"
    notifier.username = 'bunny'
    notifier.ping "Company Created"
    notifier.ping self.name
    notifier.ping self.email
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @organization = current_user.organization
    @companies = @organization.companies
    @company = Company.new

    @companies = @companies.where(email: params[:email]) if params[:email].present?
    @companies = @companies.where(name: params[:name]) if params[:name].present?

    respond_to do |format|
        format.html
        format.js
      end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    @feeds = @company.feeds
    @tasks = @company.tasks.where("is_completed = ?", false)
    @task = @company.tasks.new
    @note = @company.notes.new
    @user = current_user
    @users = @user.organization.users

    @opt = [{"name"=>"All", "id"=>"001"},{"name"=>"notes", "id"=>"002"}, {"name"=>"tasks", "id"=>"003"}]
    @feeds = @company.feeds if params[:option]=="001"
    @feeds = @company.feeds.where(feedable_type: "Note") if params[:option]=="002"
    @feeds = @company.feeds.where(feedable_type: "Task") if params[:option]=="003"

    respond_to do |format|
        format.html
        format.js
      end


  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.mobile_numbers.new

    respond_to do |format|
        format.html
        format.js
      end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
    respond_to do |format|
        format.html
        format.js
      end
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    @company.mobile_numbers.each do |t|
      t.company_id = @company.id
    end

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.js {  flash[:notice] = "Company Created" }

        format.json { render :show, status: :created, location: @company }
      else
        puts '>>>>>>', @company.errors.inspect
        format.html { render :new }
        format.js
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.js
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def feed_destroy

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :email, :address, :contact, :organization_id, mobile_numbers_attributes: [:id, :number, :_destroy])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<tr data-company-id='<%= company.id%>'>
  <td>
    <div class="media">
      <div class="media-left">
        <h3><strong><%= icon 'building' %></strong></h3><br/>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to company.name, company %>
        </h4>
          <%=icon 'phone' %>&nbsp;&nbsp;<%= company.contact %>
          <br/>


          <small><%= link_to edit_company_path(company),
          remote: true,'data-toggle': "modal",'data-target': "#myModal" do %>
            <%= icon 'pencil' %>
            Edit
            <%end%>
          </small>
          &nbsp;&nbsp;
          <small><%= link_to company, method: :delete,
              data: { confirm: 'Are you sure?' } do %>
              <%= icon 'trash' %>
              Delete
              <%end%>
          </small>
          &nbsp;&nbsp;
          <small>
          (<%= company.organization.name %>)
        </small>
        </div>
      </div>
  </td>
</tr>

app/views/companies/_error.html.erb
<% if @company.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>
        <ul>
          <% @company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
   </div>
 <% end %>

app/views/companies/_feed.html.erb
 <tr data-company-feed-id='<%= feed.id%>'>
  <td>
    <div class="media">
      <div class="media-left">
        <%if feed.feedable_type=="Note" %>
          <%= icon 'sticky-note' %>
          <% else %>
          <%= icon 'check-square' %>
        <% end %><br/>
      </div>
      <div class="media-body">
          <h4 class="media-heading"><%= feed.content %></h4>
             <%= feed.created_at.to_formatted_s(:long) %><br/>


              <%if feed.feedable_type=='Note' %>
                 <strong><%= link_to edit_company_note_path(feed.company_id, feed.feedable_id),
                 remote: true,'data-toggle': "modal",'data-target': "#myModal" do %>
                 <%= icon 'pencil'%>
                 Edit
                 <%end%>
                 </strong>
                 &nbsp;&nbsp;

                  <strong><%= link_to company_note_path(feed.company_id, feed.feedable_id),
                  method: :delete, data: { confirm:'Are you sure?' }, remote: true do %>
                  <%= icon 'trash' %>
                  Delete
                  <%end%>
                  </strong>
                  &nbsp;&nbsp;
              <%else%>
                  <strong><%= link_to edit_company_task_path(feed.company_id,feed.feedable_id),
                  remote: true, 'data-toggle': "modal",'data-target': "#myModal" do %>
                  <%= icon 'pencil'%>
                  Edit
                  <%end%>
                  </strong>
                  &nbsp;&nbsp;

                  <strong><%= link_to company_task_path(feed.company_id,feed.feedable_id),
                   method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                   <%= icon 'trash' %>
                   Delete
                   <%end%>
                  </strong>
                  &nbsp;&nbsp;
                <%end%>
                <strong><%= feed.organization.name %><br/></strong>
            </div>
      </div>
  </td>
</tr>

app/views/companies/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_for company, html: { id: 'new_company' }, remote: true do |f| %>

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Company</h4>
      </div>

      <% if company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>
              <ul>
                <% company.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
              </ul>
         </div>
       <% end %>


  <div class="modal-body">

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name,class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true,class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_area :address,class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :contact %>
      <%= f.text_field :contact,class: "form-control" %>
    </div>

    <div id="Mobile">
        <%= f.label "Mobile Number" %>
        <%= f.fields_for :mobile_numbers do |mobile_number| %>
          <%= render 'mobile_number_fields', f: mobile_number %>
        <% end %>

        <div class="links">
        <%= link_to_add_association 'add Number', f, :mobile_numbers %>
        </div>
  </div>

      <%= f.hidden_field :organization_id, value: current_user.organization_id %>
    </div>

  <div class="modal-footer">

    <div class="form-group">
      <%= f.submit class: "btn btn-default btn-success form-control"%>
    </div>
  </div>

    <% end %>
  </div>
</div>

app/views/companies/_mobile_number_fields.html.erb
<div class="nested-fields">
  <div class="fields">

    <%= f.text_field :number, class: "form-control" %>

      <div>
          <%= link_to_remove_association "remove number", f %>
      </div>
  </div>
</div>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/edit.js.erb
$('#myModal').html('<%= j render partial:'form', :locals => {:company => @company } %>')

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <h1>
      <strong>Company</strong>
      <%= link_to "New Company", new_company_path, id: 'new_link',remote: true,
      'data-toggle': "modal",'data-target': "#myModal",
      class: "btn btn-primary pull-right" %>
    </h1>
  </div>
</div>
<br/>

<div class="row">
  <div class="col-md-12">
    <%= form_tag companies_path, method: :get, class: "form-inline",id: "search" ,remote: :true do %>
      <div class="form-group">
        <%= email_field_tag :email, params[:email],class: "form-control",
        placeholder: "email"%>
       </div>

       <div class="form-group">
         <%= text_field_tag :name, params[:name],class:"form-control",
         placeholder: "name"%>
        </div>

        <!-- <div class="form-group">
          <%= submit_tag "Search", class: "btn" %>
        </div> -->
      <% end %>
  </div>
</div>
<br/>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <table id="company" class="table table-striped table-bordered table-hover">
        <tbody>
          <%= render @companies %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/companies/index.js.erb
$("#company").html("<%= j render @companies %>")

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/new.js.erb
 // $('#new_link').hide().after('<%= j render partial:'form', :locals => {:company => @company } %>')

 $('#myModal').html('<%= j render partial:'form', :locals => {:company => @company } %>')

app/views/companies/show.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>

  <!-- <div class="row">
      <%= link_to 'New Notes ', new_company_note_path(@company),remote: true, 'data-toggle': "modal",'data-target': "#myModal",class: "pull-right", style: 'margin-right:10px;' %>
      <%= link_to 'New Task ', new_company_task_path(@company),remote: true, 'data-toggle': "modal",'data-target': "#myModal", class: "pull-right", style: 'margin-right:10px;' %>
  </div> -->

  <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-body" style="background-color: #f5f5f5;"}
        <p>
        <h3><strong><%= @company.name %></strong></h3>
        </p>

        <p>
          <%= icon 'envelope'%>&nbsp;<strong><%= @company.email %></strong>
        </p>

        <p>
          <%= icon 'map-marker'%>&nbsp;<strong><%= @company.address %></strong>
        </p>

        <p>
          <%= icon 'phone'%>&nbsp;<strong><%= @company.contact %></strong>
        </p>

        <p>
          <%= icon 'building-o'%>&nbsp;<strong><%= @company.organization.name%></strong>
        </p>

        <p>
          <% if @company.mobile_numbers.any? %>
            <% @company.mobile_numbers.each do |mobile_number|%>
            <%= icon 'mobile' %>&nbsp;<strong><%= mobile_number.number %></strong><br/>
            <%end%>
          <%end%>
        </p>
      </div>
      </div>
  </div>

<div class="col-md-5">

<div class="container-fluid">
    <div class="row-fluid">

        <div class="span8 well">

            <ul class="nav nav-tabs">
                <li class="active pull-right"> <a data-target="#note" data-toggle="tab">Note</a></li>
                <li class="pull-right"><a data-target="#task" data-toggle="tab">Task</a></li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane active fade in" id="note"><%= render partial: "notes/form1" %></div>
                <div class="tab-pane" id="task"><%= render partial: "tasks/form1" %></div>
            </div>

        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row-fluid">
        <div>
          <%= form_tag company_path, method: :get, class: "form-inline", id: "lead_form", remote: :true do %>
            <div class="form-group">
              <%= select_tag "option", options_for_select(@opt.collect {|p| [ p['name'], p['id'] ] }, params[:option]) %>
            </div>
          <% end %>
        </div>
          <br/>
          <div class="span8 well">
            <div class="panel panel-default">
                <table class="table table-striped table-bordered table-hover" id="company_feed">

                    <tbody>
                      <%= render collection: @feeds, partial: 'feed' %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

</div>

<div class="col-md-4">

<div class="panel panel-default">
<h3 class="text-justify" > &nbsp;
Due Tasks </h3>
    <div class="panel panel-default">
        <table class="table table-striped table-bordered table-hover" id="company_task">
            <tbody>
              <%= render collection: @tasks, partial: 'tasks/task' %>
            </tbody>
        </table>
    </div>
</div>


</div>
</div>

app/views/companies/show.js.erb
$("#company_feed").html("<%= j render collection: @feeds, partial: 'feed' %>")

app/views/companies/update.js.erb
<% if @company.errors.any? %>
$('#myModal').html("<%= j render partial: "error" %>")
$('#myModal').html('<%= j render partial:'form', :locals => {:company => @company } %>')

<% else %>

$('#myModal').modal("hide");
$("tr[data-company-id='<%= @company.id %>']").replaceWith('<%= j render partial:'company', :locals => {:company => @company } %>');
<%end%>