config/routes.rb
Rails.application.routes.draw do

  resources :companies do
      resources :notes
        resources :tasks do
          member do
            put :complete
            delete :feed_destroy
          end
      end
   end

   resources :organizations do
     get 'search'
   end

   root to: "staticpages#index"

   resources :feeds, only: :index
   get 'staticpages/index'
   get 'staticpages/show'



   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        invitations: 'users/invitations'
      }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand" href="#">CRM</a>
    </div>

<% if user_signed_in? %>

    <div class="collapse navbar-collapse navbar-left" id="bs-example-navbar-collapse-1">
        <%= link_to feeds_path,class: "active",class: "navbar-text" do %>
          <%=icon 'list'%>
          feeds
        <%end%>
        <%=link_to companies_path,class: "active",class:"navbar-text" do %>
          <%=icon 'building'%>
          Company
        <%end%>
        <%=link_to organizations_path,class: "active",class:"navbar-text" do %>
          <%=icon 'check-square'%>
          Tasks
        <%end%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%=icon 'cog'%><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">

            <li><%= link_to "Profile",staticpages_show_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Edit",edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>

          </ul>
        </li>
      </ul>
    </div>
<% else %>

    <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Login", new_user_session_path %></li>
    <li role="separator" class="divider"></li>
    <li><%= link_to "Password Reset", new_user_password_path(current_user)%></li>
    </ul>

    <% end %>


    </div><!-- /.navbar-collapse -->
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name%> <%= action_name%>">
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
    <%= yield %>

  <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    </div>

  </body>
</html>